[features]
seeds = false
skip-lint = false

[programs.localnet]
dynamic_bonding_curve = "dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "NODE_OPTIONS=--no-experimental-strip-types yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
ixdata = "yarn run tsx --tsconfig ./tsconfig.json ./scripts/generate_ix_data_for_tests.ts"

[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.13"
