name: "Setup anchor-cli"
description: "Setup anchor cli"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      name: Cache Anchor CLI
      id: cache-anchor
      with:
        path: ~/.cargo/bin/anchor
        key: anchor-cli-${{ runner.os }}-${{ env.ANCHOR_CLI_VERSION }}
    - run: cargo install --git https://github.com/coral-xyz/anchor --tag v${{ env.ANCHOR_CLI_VERSION }} anchor-cli --locked
      if: steps.cache-anchor.outputs.cache-hit != 'true'
      shell: bash
